services:
  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=ewm-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: postgres-ewm-main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  discovery-server:
    build: infra/discovery-server
    image: discovery-server
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD-SHELL", "(wget -q -O /dev/null http://localhost:8761/actuator/health || curl -sf http://localhost:8761/actuator/health) || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  config-server:
    build: infra/config-server
    image: config-server
    ports:
      - "8888:8888"
    depends_on:
      discovery-server:
        condition: service_healthy

  stats-server:
    build: stat/stats-server
    image: stats-server
    depends_on:
      stats-db:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:
      - DB_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - DB_DRIVER=org.postgresql.Driver
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
      - JPA_DDL_AUTO=create
      - SQL_INIT_MODE=never

  ewm-service:
    build: core/main-service
    image: ewm-main-service
    depends_on:
      ewm-db:
        condition: service_healthy
      config-server:
        condition: service_started
    environment:
      - DB_URL=jdbc:postgresql://ewm-db:5432/ewm
      - DB_DRIVER=org.postgresql.Driver
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      - JPA_DDL_AUTO=create
      - SQL_INIT_MODE=never

  user-service:
    build: core/user-service
    image: user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started
      ewm-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm

  gateway-server:
    build: infra/gateway-server
    image: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_started