services:
  stats-server:
    build:
      context: .
      dockerfile: stat/stat-server/Dockerfile
    image: stat-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stat-db
    ports:
      - "6541:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stat -d ewm-stats" ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=ewm-stats

  ewm-db:
    image: postgres:16.1
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ewm -d ewm" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ewm-service:
    build:
      context: .
      dockerfile: main-service/Dockerfile
    image: ewm-service
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy