#services:
#  stats-server:
#    build:
#      context: stat/stat-server
#      dockerfile: Dockerfile
#    image: stat-server
#    ports:
#      - "9090:9090"
#    depends_on:
#      - stats-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
#      - SPRING_DATASOURCE_USERNAME=stat
#      - SPRING_DATASOURCE_PASSWORD=stat
#
#  stats-db:
#    image: postgres:16.1-alpine
#    container_name: postgres-ewm-stat-db
#    ports:
#      - "6541:5432"
#    environment:
#      - POSTGRES_PASSWORD=stat
#      - POSTGRES_USER=stat
#      - POSTGRES_DB=ewm-stats
#
#  ewm-db:
#    image: postgres:16.1-alpine
#    ports:
#      - "6542:5432"
#    environment:
#      - POSTGRES_PASSWORD=ewm
#      - POSTGRES_USER=ewm
#      - POSTGRES_DB=ewm
#
#  ewm-service:
#    build:
#      context: main-service
#      dockerfile: Dockerfile
#    image: ewm-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ewm-db
#      - stats-server
#    environment:
#      - STATS_SERVER_URL=http://stats-server:9090
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
#      - SPRING_DATASOURCE_USERNAME=ewm
#      - SPRING_DATASOURCE_PASSWORD=ewm
services:
  stats-server:
    build: stat/stat-server
    image: stat-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=stat

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=stat
      - POSTGRES_USER=stat
      - POSTGRES_DB=ewm-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: main-service
    image: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_DB=ewm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10