server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: ewm-request-service-user-requests
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**
        - id: ewm-request-service-admin
          uri: lb://request-service
          predicates:
            - Path=/admin/requests/**
        - id: ewm-event-service-user-events
          uri: lb://event-service
          predicates:
            - Path=/users/*/events/**
        - id: ewm-event-service-admin
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**
        - id: ewm-user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: ewm-user-service-public
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: ewm-event-service-public
          uri: lb://event-service
          predicates:
            - Path=/events/**
        - id: ewm-main-service-admin
          uri: lb://main-service
          predicates:
            - Path=/admin/**
        - id: ewm-main-service-categories
          uri: lb://main-service
          predicates:
            - Path=/categories/**
        - id: ewm-main-service-compilations
          uri: lb://main-service
          predicates:
            - Path=/compilations/**