server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:

        - id: ewm-user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: ewm-user-service-public
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: ewm-main-service-admin
          uri: lb://main-service
          predicates:
            - Path=/admin/**

        - id: ewm-main-service-events
          uri: lb://main-service
          predicates:
            - Path=/events/**

        - id: ewm-main-service-categories
          uri: lb://main-service
          predicates:
            - Path=/categories/**

        - id: ewm-main-service-compilations
          uri: lb://main-service
          predicates:
            - Path=/compilations/**