spring:
  application:
    name: gateway-server
  config:
    import:
      - "optional:configserver:http://localhost:8888"
      - "optional:configserver:http://config-server:8888"

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info