spring:
  datasource:
    username: ${POSTGRES_USER:sa}
    password: ${POSTGRES_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  sql:
    init:
      mode: ${SQL_INIT_MODE:always}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true

feign:
  client:
    config:
      default:
        connectTimeout: 2000  # 2 секунды на установку соединения
        readTimeout: 5000     # 5 секунд на ожидание ответа
  circuitbreaker:
    enabled: true